### ISSUE TITLE
Qual tipo pagamentos ele aceita

### ISSUE THREAD

**Issue by ZuchiVictor** [zucchi25/Source-Code-Inspection#3]
Qual tipo de pagamento o cliente poderá fazer, poderá usar cédulas? ,moedas? ,ambas juntas, e como ele ira verificar se a cédula e verdadeira.

**Comment by zucchi25** [comment]
Qual tipo de pagamento o cliente poderá fazer, poderá usar cédulas? ,moedas? ,ambas juntas, e como ele ira verificar se a cédula e verdadeira.

**Comment by ZuchiVictor** [comment]
https://github.com/zucchi25/Source-Code-Inspection/wiki
