### ISSUE TITLE
Erro no if do papelmoeda

### ISSUE THREAD

**Issue by ZuchiVictor** [zucchi25/Source-Code-Inspection#6]
if(papelmoeda[1] = = quantia) {
possui = true;
}

O erro esta em papelmoeda[1] que deveria ser papelmoeda[i]

**Comment by zucchi25** [comment]
https://github.com/zucchi25/Source-Code-Inspection/commit/4bd2aec99506667cdadd8d5eff316e112d2afee0

**Comment by ZuchiVictor** [comment]
https://github.com/zucchi25/Source-Code-Inspection/commit/4bd2aec99506667cdadd8d5eff316e112d2afee0
